### ISSUE TITLE
Search box in specs.frictionlessdata.io not working (as I expected)

### ISSUE THREAD

**Issue by cpina** [frictionlessdata/website#187]
Steps to reproduce:
-Open https://specs.frictionlessdata.io/#overview
-In the search box type "zip" and press enter

Expected:
-List of pages with the term "zip" or a "no pages contain the term zip"

Actual:
-Nothing happens :-(

After doing this I realised that if I type "a" (or a single letter) it shows the list of headers. Or if I type "adding" it shows the headers having "adding" in the title. But this is not what I expected initially obviously.

**Comment by aivuk** [comment]
@cpina Thanks! The first example "zip" currently show results, probably fixed since you wrote the issue (almost two years!). But I agree that it would be better to display a message like "not found" when there are no results. I also agree that a minimum number of characters to be typed before searching is a nice feature.

@mccalluc Currently the Frictionless framework documentation is at https://framework.frictionlessdata.io/ where the search has improved a lot since your reported this issue.

**Comment by roll** [comment]
Thanks @aivuk!

I've create an issue for it - https://github.com/frictionlessdata/specs/issues/788

Closing this one as resolved
