### ISSUE TITLE
Using blue color for links instead of red?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/website#209]
Hi,

@rufuspollock 
@lwinfree 
@sglavoie 
@sapetti9 

I've been working a lot on the website lately and still can get used to the red color of the links and hovers. TBH red is usually associated with danger/errors/etc (e.g. [Bootstrap Button](https://getbootstrap.com/docs/4.0/components/buttons/)) so it might be the reasons why it doesn't feel natural at least for me.

If we compare the main website and the specs:
- https://frictionlessdata.io/adoption/#grant-funded-work
- https://specs.frictionlessdata.io/tabular-data-resource/#introduction

The latter in my eyes is more comfortable to read.

WDYT? Does someone have a similar perception? Shall we ask users to confirm that it's OK/not OK?

**Comment by sglavoie** [comment]
@roll since you asked, here are some of my observations :smile: :

### Current theme with orange

The contrast can't be high enough with a white background according to the [WebAIM contrast checker](https://webaim.org/resources/contrastchecker/): otherwise, the color needs to be much closer to red than to orange. This can be seen with the [checker tool here](https://webaim.org/resources/contrastchecker/?fcolor=EA6D4C&bcolor=FFFFFF).

![current_orange](https://user-images.githubusercontent.com/32682903/123272905-cdb98500-d4c7-11eb-925f-47e97b842b77.png)

Orange: `#EA6D4C`

A clear orange would work well with a dark theme if this is ever considered as an alternative:

![dark_theme](https://user-images.githubusercontent.com/32682903/123273136-fccff680-d4c7-11eb-9638-2d33604b1da7.png)

Clear orange: `#ff9a00`

### Theme with blue

With a white background, blue is a clear winner in my view. However, the current tint of blue [also lacks some contrast](https://webaim.org/resources/contrastchecker/?fcolor=1A98FF&bcolor=FFFFFF).

#### Current theme with blue

![current_blue](https://user-images.githubusercontent.com/32682903/123273621-6cde7c80-d4c8-11eb-9cec-b9b8f0a02b80.png)

This color would also work [a lot better for a dark theme](https://webaim.org/resources/contrastchecker/?fcolor=1A98FF&bcolor=000000).

Blue: `#1A98FF`

#### Proposed modifications

The fine tuning of the colors is of course up to you, but I think something like this can be achieved:

![new_blue](https://user-images.githubusercontent.com/32682903/123273751-88e21e00-d4c8-11eb-8994-79600ea1456b.png)

This would be done by taking the orange from the logo, making it dark enough and taking its complementary color:
![2021-06-24_08-18](https://user-images.githubusercontent.com/32682903/123273810-94cde000-d4c8-11eb-966d-3b887a1c454d.png)

Then, for the links in the navbar and sidebar to shine a bit more, contrast can be dropped a bit on the inactive links by choosing a different tint:

![2021-06-24_08-31](https://user-images.githubusercontent.com/32682903/123274046-c9da3280-d4c8-11eb-8b2e-7ddfed61d70d.png)

New blue: `#007A9A`
New navbar/sidebar inactive color (grayish blue): `#616E7C`

[This color picker tool](https://htmlcolorcodes.com/color-picker/) could be helpful to experiment.

**Comment by lwinfree** [comment]
this is SO helpful @sglavoie! thank you for all this info!

**Comment by roll** [comment]
MERGED into frictionlessdata/frictionlessdata.io#757
